title: Joshua S. Cárdenas C. | Tech Lead & AI Engineer
logo: /assets/img/head_shot_circle.jpg
description: Electronics Engineer transitioning into advanced Software Engineering, Artificial Intelligence, and Data Science.
show_downloads: false # Lo puse en false porque añadí un botón más bonito en el HTML arriba. Si quieres el default, ponlo en true.
theme: jekyll-theme-minimal
github:
  is_project_page: false
